<?php

/**
 * @file
 * Hook implementations for the novartis_widen_image module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function novartis_widen_image_theme() {
  return [
    'widen_image_formatter' => [
      'variables' => [
        'widen_embed_code' => NULL,
      ],
      'template' => 'widen-image-formatter',
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function novartis_widen_image_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'media_widen_edit_form':
    case 'media_widen_add_form':
      // Add a custom submit handler to validate the widen image source code.
      $form['#validate'][] = 'novartis_widen_image_media_submit';
      break;
  }
}

/**
 * Helper function to validate widen image source code.
 */
function novartis_widen_image_media_submit(array &$form, FormStateInterface $form_state) {
  $source_code = $form_state->getValue('field_media_widen_image');

  if (!(\Drupal::service('novartis_widen_image.widen_image_validation')->validateWidenImage($source_code[0]['value']))) {
    // Set form error.
    $form_state->setErrorByName('field_media_widen_image', 'Enter a valid widen image source code.');
  }
}
